### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by yazanomi** [Ben-Schr/osu-most-played-downloader#1]
Tried to use this recently and ran into some troubles...

I believe this API is down?
https://api.chimu.moe/v1/download/71561

Not sure if this is related to you... 
![image](https://github.com/user-attachments/assets/bdad53f0-ffb8-4f40-985e-233aed3d7f6e)

**Comment by Ben-Schr** [comment]
Thanks for bringing that up, I almost forgot I even made this thing. It seems like his API is no longer in service because they switched to a new URL and API schema. The latest changes should have fixed the problem and also added some other changes (mostly to the way you enter your data).
